version: "3"
services:
  api-project-write:
    build:
      context: ./project_service_write
      args:
        NODE_ENV: ${NODE_ENV}
    entrypoint: npm run ${NODE_CMD}
    environment:
      - mongodbConStr=mongodb://mongodb/project_service_write
    volumes:
      - ./project_service_write/src:/app/src
      - ./libraries:/libraries
    networks:
      - default
      - thesisfair
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    command: --quiet --logpath /dev/null
    restart: unless-stopped

    ports:
      - 27017:27017

networks:
  thesisfair:
    name: thesisfair
    external: true
