version: "3"
services:
  event_service:
    build:
      context: ./event_service
      args:
        NODE_ENV: ${NODE_ENV}
    entrypoint: npm run ${NODE_CMD}
    volumes:
      - ./event_service/src:/app/src
      - ./libraries:/libraries
    networks:
      - default
      - thesisfair
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    command: --quiet --logpath /dev/null
    restart: unless-stopped

    ports:
      - 27017:27017

networks:
  thesisfair:
    name: thesisfair
    external: true
