version: "3"
services:
  event_service:
    build:
      context: .
      args:
        NODE_ENV: development
    entrypoint: npm run start
    environment:
      - rabbitmqUsername=guest
      - rabbitmqPassword=guest
    volumes:
      - ./src:/app/src
    networks:
      - default
      - thesisfair
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always

    ports:
      - 27017:27017

    logging:
      driver: none

networks:
  thesisfair:
    name: thesisfair
    external: true
