apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      service: api-gateway
      dependency: main
  # replicas: 2
  template:
    metadata:
      labels:
        service: api-gateway
        dependency: main
    spec:
      containers:
      - name: api-gateway
        image: ghcr.io/quinten1333/thesisfair-api_gateway
        ports:
        - containerPort: 80
        env:
          - name: amqpConStr
            value: amqp://guest:guest@rabbitmq
          - name: jwtKey
            value: ojbbXCBUC2u2TpHmL4Y/NEnZutD8eCef1pcJ9K8OEvm5NwPJA8IB30Z129W4+gYXntiTA4434aK1SbjxR18Mut+aj6wucQfIwQIewl1Lp0xnwxFpvZ+hi0Y4cucgL5bJBWQL3yGd2JVR9S4BNwfn/oYINsvraVbfy+2caEswKc1JGKpBy0XpuTzXLc9nX7ahWvD7dGY2gwzTRPmIdJX87t0M2/WEV7jd+jP8YeO2AB6Bh9YeHXlANOwtFK/Be4NGpZNRusNLh0Smf0QcABgBCn7UyMTSsigYN21+rKz7X+lzGej7GYY8VWKco0v09KYiigi54oRAQcfkfn5mTEF2Zxrn5Lgngx4WYEuZ2399rSor1Q/TYV9mGF4Gep8PjG2jzjWA1fJrqYcgWhgUfzHSKywZ7ftDXubH2YX2BlCUIIwBxqF6yKqisdnl5Uql9VepqW9am5fXFkGZpvvZbniHWnrSw6FQnXPQvzhYjASwNTl/cXTSO52L+pxW7WVGOufa9qJ+JMSLSs0ZtnhHDTYFnygqu+07K01FCsedfkhFgdFf7ldIzzBpHEyd9I5eqFJ/UTftvwt1qSbYJqA6q+aI0RS1SPUSFWuynpW6KD2e3yHLgBCcox23TT8Fkm5rA3En8032pg642v6xHjNEARbe9pCrSCGCdJbJtgvBi94LC+U=
        resources:
          requests:
            cpu: 0.45
            memory: 128Mi
        imagePullPolicy: Always
      - name: sidecar
        image: ghcr.io/quinten1333/thesisfair-sidecar
        env:
        - name: amqpConStr
          value: amqp://guest:guest@rabbitmq
        - name: queue
          value: api-gateway
        resources:
          requests:
            cpu: 0.05
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regghcr

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-api-gateway
  labels:
    service: api-gateway
    dependency: main
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
  selector:
    service: api-gateway
    dependency: main

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api-gateway

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  service-api-gateway
                port:
                  number: 80
