version: "3"
services:
  api_gateway:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    entrypoint: npm run ${NODE_CMD}
    ports:
      - "3000:80"
    volumes:
      - ./API_gateway/src:/app/src
      - ./API_gateway/test:/app/test
    networks:
      - thesisfair

networks:
  thesisfair:
    name: thesisfair
    external: true
