version: "3"
services:
  api_gateway:
    build:
      context: .
      args:
        NODE_ENV: development
    entrypoint: npm run start
    ports:
      - "3000:80"
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    networks:
      - thesisfair

networks:
  thesisfair:
    name: thesisfair
    external: true
