version: "3"
services:
  api_gateway:
    build: .
    entrypoint: npm run start
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    networks:
      - thesisfair

networks:
  thesisfair:
    name: thesisfair
    external: true
