apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      service: api-gateway
      dependency: main
  # replicas: 2
  template:
    metadata:
      labels:
        service: api-gateway
        dependency: main
    spec:
      containers:
      - name: api-gateway
        image: ghcr.io/quinten1333/thesisfair-api_gateway
        ports:
        - containerPort: 80
        env:
          - name: amqpConStr
            value: amqp://guest:guest@rabbitmq
        resources:
          requests:
            cpu: 0.1
            memory: 128Mi

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75

---

apiVersion: v1
kind: Service
metadata:
  name: service-api-gateway
  labels:
    service: api-gateway
    dependency: main
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
  selector:
    service: api-gateway
    dependency: main
