apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: event-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
spec:
  selector:
    matchLabels:
      service: event-service
      dependency: main
  template:
    metadata:
      labels:
        service: event-service
        dependency: main
    spec:
      containers:
      - name: event-service
        image: ghcr.io/quinten1333/thesisfair-event_service:base
        env:
          - name: mongodbConStr
            value: mongodb://service-event-service-mongodb/event_service
          - name: amqpConStr
            value: amqp://guest:guest@rabbitmq
        resources:
          requests:
            cpu: 0.2
            memory: 128Mi
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/app/data"
          name: event-storage
      volumes:
      - name: event-storage
        persistentVolumeClaim:
          claimName: event-storage

      imagePullSecrets:
      - name: regghcr

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: event-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: event-service
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-event-service-mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
      service: event-service
      dependency: mongodb

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: event-service-mongodb
spec:
  serviceName: service-event-service-mongodb
  replicas: 1

  selector:
    matchLabels:
      service: event-service
      dependency: mongodb
  template:
    metadata:
      labels:
        service: event-service
        dependency: mongodb
    spec:
      containers:
      - name: event-service-mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data-event-service-mongodb
          mountPath: /data/db
        imagePullPolicy: IfNotPresent

  volumeClaimTemplates:
  - metadata:
      name: data-event-service-mongodb
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
