entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: webSec
          scheme: https
  webSec:
    address: ":443"
    http:
      tls: {}

providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    directory: /dynamic-config
    watch: true

accessLog: {}

api:
  insecure: true
