apiVersion: apps/v1
kind: Deployment
metadata:
  name: $serviceName
spec:
  selector:
    matchLabels:
      service: $serviceName
      dependency: main
  replicas: 2
  template:
    metadata:
      labels:
        service: $serviceName
        dependency: main
    spec:
      containers:
      - name: $serviceName
        image: ghcr.io/quinten1333/thesisfair-$imagePostFix
        env:
          - name: mongodbConStr
            value: mongodb://service-$serviceName-mongodb/$imagePostFix
          - name: amqpConStr
            value: amqp://guest:guest@rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  name: service-$serviceName-mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
      service: $serviceName
      dependency: mongodb

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: $serviceName-mongodb
spec:
  serviceName: service-$serviceName-mongodb
  replicas: 1

  selector:
    matchLabels:
      service: $serviceName
      dependency: mongodb
  template:
    metadata:
      labels:
        service: $serviceName
        dependency: mongodb
    spec:
      containers:
      - name: $serviceName-mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data-$serviceName-mongodb
          mountPath: /data/db

  volumeClaimTemplates:
  - metadata:
      name: data-$serviceName-mongodb
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
