version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'rabbitmq'
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/11-custom.conf
    ports:
      - 15672:15672
    networks:
      - thesisfair

  traefik:
    image: traefik:2.8
    restart: unless-stopped
    ports:
      - 3001:80
      - 3002:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - thesisfair

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - thesisfair

networks:
  thesisfair:
    name: thesisfair
