version: "3"
services:
  frontend:
    build:
      context: ./frontend_service
      dockerfile: Dockerfile-dev
      args:
        NODE_ENV: ${NODE_ENV}
    entrypoint: npm run ${NODE_CMD}
    environment:
      - PORT=3001
    ports:
      - 3001:3001
    volumes:
      - ./frontend_service/node_modules:/app/node_modules
      - ./frontend_service/public:/app/public:ro
      - ./frontend_service/src:/app/src:ro
      - ./libraries/thesisfair-api/:/app/node_modules/@amicopo/thesisfair-api/:ro
