apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      service: api-gateway
  replicas: 2
  template:
    metadata:
      labels:
        service: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: ghcr.io/quinten1333/thesisfair-api_gateway
        ports:
        - containerPort: 80
        env:
          - name: amqpConStr
            value: amqp://guest:guest@rabbitmq
          - name: DEBUG
            value: API_gateway:*

---

apiVersion: v1
kind: Service
metadata:
  name: service-api-gateway
  labels:
    service: api-gateway
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
    protocol: TCP
  selector:
    service: api-gateway
